defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  timeout: 5000
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *defaults
  database: skywyre_development

test:
  <<: *defaults
  database: skywyre_test

production:
  <<: *defaults
  database: skywyre